-- Database: u632324167_qs
CREATE DATABASE IF NOT EXISTS `u632324167_qs` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `u632324167_qs`;

-- Table structure for table `admin_users`
CREATE TABLE IF NOT EXISTS `admin_users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(191) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Dumping data for table `admin_users`
-- Default password: QSmarketing@1
INSERT INTO `admin_users` (`email`, `password_hash`) VALUES
('admin@qsmarketingexperts.online', '$2y$10$rmoDlOyTo5FoN0qAagFMweSPO75ETSij5ME7i9.ljbtaeeOUp7HG.');

-- Table structure for table `portfolio_categories`
CREATE TABLE IF NOT EXISTS `portfolio_categories` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(191) NOT NULL,
  `slug` VARCHAR(191) NOT NULL UNIQUE,
  `icon_class` VARCHAR(191) NOT NULL,
  `sort_order` INT DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Dumping data for table `portfolio_categories`
INSERT INTO `portfolio_categories` (`name`, `slug`, `icon_class`, `sort_order`) VALUES
('Social Media', 'social-media', 'fa-solid fa-hashtag', 1),
('FB & Instagram Ads', 'facebook-instagram', 'fa-brands fa-meta', 2),
('Google Ads', 'google-ads', 'fa-brands fa-google', 3),
('SEO', 'seo', 'fa-solid fa-magnifying-glass-chart', 4),
('Web Development', 'web-dev', 'fa-solid fa-code', 5),
('Graphic Design', 'graphic-design', 'fa-solid fa-pen-nib', 6),
('Content', 'content', 'fa-solid fa-file-lines', 7),
('Branding', 'branding', 'fa-solid fa-layer-group', 8),
('Lead Gen', 'lead-gen', 'fa-solid fa-funnel-dollar', 9),
('Email', 'email', 'fa-solid fa-envelope-open-text', 10),
('E-commerce', 'ecommerce', 'fa-solid fa-cart-shopping', 11),
('Video Editing', 'video', 'fa-solid fa-video', 12);

-- Table structure for table `portfolio_items`
CREATE TABLE IF NOT EXISTS `portfolio_items` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `category_id` INT NOT NULL,
  `title` VARCHAR(191) NOT NULL,
  `subtitle` VARCHAR(255) NOT NULL,
  `image_url` TEXT NOT NULL,
  `link_url` TEXT NULL,
  `sort_order` INT DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`category_id`) REFERENCES `portfolio_categories`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Dumping data for table `portfolio_items`
-- Note: category_id values here assume the IDs generated by the auto-increment starting from 1 in the order of insertion above.
INSERT INTO `portfolio_items` (`category_id`, `title`, `subtitle`, `image_url`, `link_url`, `sort_order`) VALUES
(1, 'Instagram Growth Campaign', '+180K followers in 90 days', 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?auto=format&fit=crop&w=500&q=80', NULL, 1),
(1, 'TikTok Viral Campaign', '5.2M views in 1 month', 'https://images.unsplash.com/photo-1626446174620-444af74461c7?auto=format&fit=crop&w=500&q=80', NULL, 2),
(1, 'LinkedIn B2B Strategy', '320% engagement increase', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=500&q=80', NULL, 3),
(1, 'Community Engagement', '45K qualified leads generated', 'https://images.unsplash.com/photo-1559027615-cd2628902d4a?auto=format&fit=crop&w=500&q=80', NULL, 4),
(1, 'Content Calendar Execution', '6 months of consistent posting', 'https://images.unsplash.com/photo-1611162617305-c69b3fa7fbe0?auto=format&fit=crop&w=500&q=80', NULL, 5),
(1, 'Influencer Collaboration', '8.5M combined reach', 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=500&q=80', NULL, 6),
(2, 'E-commerce Sales Campaign', '3.8x ROAS | $420K revenue', 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=500&q=80', NULL, 7),
(2, 'Lead Generation Funnel', '$8 cost per lead | 420 leads', 'https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=500&q=80', NULL, 8),
(2, 'Video Ad Campaign', '12% video view-through rate', 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=500&q=80', NULL, 9),
(2, 'Retargeting Optimization', '28% conversion uplift', 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=500&q=80', NULL, 10),
(2, 'Audience Segmentation', '6 custom audience tiers', 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=500&q=80', NULL, 11),
(2, 'Carousel Ad Testing', '18% CTR improvement', 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=500&q=80', NULL, 12),
(3, 'Search Ad Campaign', '4.2x ROAS | 2,300 conversions', 'https://images.unsplash.com/photo-1516321318423-f06f70504c38?auto=format&fit=crop&w=500&q=80', NULL, 13),
(3, 'Shopping Campaign', '$1.2M revenue | 68% YoY', 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=500&q=80', NULL, 14),
(3, 'YouTube Ad Placement', '92M impressions | 2.1% CTR', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=500&q=80', NULL, 15),
(3, 'Display Network Expansion', '320K impressions daily', 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=500&q=80', NULL, 16),
(3, 'Bid Strategy Optimization', '$4.20 avg CPC reduction', 'https://images.unsplash.com/photo-1516321318423-f06f70504c38?auto=format&fit=crop&w=500&q=80', NULL, 17),
(3, 'Keyword Expansion', '560 high-intent keywords', 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=500&q=80', NULL, 18),
(4, 'Organic Traffic Growth', '+240% in 6 months', 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=500&q=80', NULL, 19),
(4, 'Keyword Rankings', '152 keywords in top 10', 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=500&q=80', NULL, 20),
(4, 'Technical SEO Audit', '45 critical issues fixed', 'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=500&q=80', NULL, 21),
(4, 'Content Cluster Strategy', '68 pillar pages + clusters', 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=500&q=80', NULL, 22),
(4, 'Link Building Campaign', '420 high-authority backlinks', 'https://images.unsplash.com/photo-1516321318423-f06f70504c38?auto=format&fit=crop&w=500&q=80', NULL, 23),
(4, 'Local SEO Optimization', '1,200 local searches/month', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=500&q=80', NULL, 24),
(5, 'Conversion Funnel Website', '32% conversion rate', 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=500&q=80', NULL, 25),
(5, 'E-commerce Platform', '$2.1M annual sales', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=500&q=80', NULL, 26),
(5, 'Landing Page Suite', '12 high-converting pages', 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?auto=format&fit=crop&w=500&q=80', NULL, 27),
(5, 'Mobile-First Design', '98/100 Lighthouse score', 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=500&q=80', NULL, 28),
(5, 'CRM Integration', '2,400 leads/month captured', 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=500&q=80', NULL, 29),
(5, 'Performance Optimization', '2.1s load time | 42% faster', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=500&q=80', NULL, 30),
(6, 'Brand Identity System', 'Logo + 40 brand assets', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=500&q=80', NULL, 31),
(6, 'Ad Creatives Suite', '180 ad banners & variations', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=500&q=80', NULL, 32),
(6, 'Infographic Design', '28 data visualizations', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=500&q=80', NULL, 33),
(6, 'Social Media Templates', '120 ready-to-use designs', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=500&q=80', NULL, 34),
(6, 'Packaging Design', '3 product lines designed', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=500&q=80', NULL, 35),
(6, 'Email Newsletter Design', '24 issue template set', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=500&q=80', NULL, 36),
(7, 'Blog Content Strategy', '120 SEO-optimized posts', 'https://images.unsplash.com/photo-1455849318169-8381d78b3b69?auto=format&fit=crop&w=500&q=80', NULL, 37),
(7, 'Copywriting Services', '42 conversion-focused pieces', 'https://images.unsplash.com/photo-1455849318169-8381d78b3b69?auto=format&fit=crop&w=500&q=80', NULL, 38),
(7, 'Whitepaper & Case Study', '8 in-depth reports', 'https://images.unsplash.com/photo-1455849318169-8381d78b3b69?auto=format&fit=crop&w=500&q=80', NULL, 39),
(7, 'Social Media Captions', '480 monthly posts', 'https://images.unsplash.com/photo-1455849318169-8381d78b3b69?auto=format&fit=crop&w=500&q=80', NULL, 40),
(7, 'Email Newsletter', '52 weekly issues', 'https://images.unsplash.com/photo-1455849318169-8381d78b3b69?auto=format&fit=crop&w=500&q=80', NULL, 41),
(7, 'Press Release Series', '12 high-impact releases', 'https://images.unsplash.com/photo-1455849318169-8381d78b3b69?auto=format&fit=crop&w=500&q=80', NULL, 42),
(8, 'Complete Brand Rebrand', 'Identity + messaging + guidelines', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=500&q=80', NULL, 43),
(8, 'Brand Positioning Strategy', 'Market analysis + roadmap', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=500&q=80', NULL, 44),
(8, 'Brand Guidelines Document', '120-page comprehensive manual', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=500&q=80', NULL, 45),
(8, 'Corporate Identity', 'Logo + stationery suite', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=500&q=80', NULL, 46),
(8, 'Brand Voice Training', 'Tone guide + content standards', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=500&q=80', NULL, 47),
(8, 'Brand Audit & Evolution', 'Competitive analysis + refresh', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=500&q=80', NULL, 48),
(9, 'Full Funnel Campaign', '3,200 qualified leads', 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=500&q=80', NULL, 49),
(9, 'Landing Page Optimization', '42% conversion improvement', 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=500&q=80', NULL, 50),
(9, 'Lead Magnet Strategy', '6 high-converting offers', 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=500&q=80', NULL, 51),
(9, 'Lead Scoring System', '4 qualification tiers', 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=500&q=80', NULL, 52),
(9, 'CRM Automation', '12 automated workflows', 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=500&q=80', NULL, 53),
(9, 'Lead Nurture Campaign', '8-email drip sequence', 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=500&q=80', NULL, 54),
(10, 'Email Automation Funnel', '32% open rate | 8.2% CTR', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=500&q=80', NULL, 55),
(10, 'Newsletter Series', '52 weekly editions | 24K subscribers', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=500&q=80', NULL, 56),
(10, 'Behavioral Triggers', '14 automated email sequences', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=500&q=80', NULL, 57),
(10, 'A/B Testing Program', '52 subject line tests', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=500&q=80', NULL, 58),
(10, 'List Segmentation', '8 custom audience segments', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=500&q=80', NULL, 59),
(10, 'Abandoned Cart Recovery', '$184K revenue recovered', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=500&q=80', NULL, 60),
(11, 'Store Revenue Growth', '$2.1M annual | +68% YoY', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=500&q=80', NULL, 61),
(11, 'Product Page Optimization', '28% conversion uplift', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=500&q=80', NULL, 62),
(11, 'Checkout Funnel Recovery', '$420K recovered revenue', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=500&q=80', NULL, 63),
(11, 'Customer Retention', '31% repeat purchase rate', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=500&q=80', NULL, 64),
(11, 'AOV Increase Campaign', '$42 average order value +18%', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=500&q=80', NULL, 65),
(11, 'Inventory & Fulfillment', '95% order fulfillment', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=500&q=80', NULL, 66),
(12, 'Product Demo Video', '3.2M views | 12.1% CTR', 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=500&q=80', NULL, 67),
(12, 'Social Media Reels', '120 short-form videos', 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=500&q=80', NULL, 68),
(12, 'Ad Video Campaign', '42 video ad variations', 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=500&q=80', NULL, 69),
(12, 'Testimonial Series', '24 client testimonials', 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=500&q=80', NULL, 70),
(12, 'Explainer Animation', '8 animated explainers', 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=500&q=80', NULL, 71),
(12, 'Live Stream Production', '52 weekly live sessions', 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=500&q=80', NULL, 72);
